const CONVERSION_HOURS_PER_LEAVE = Number(process.env.CONVERSION_HOURS_PER_LEAVE || 8);
const AUTO_APPROVE_DAYS_BEFORE = Number(process.env.AUTO_APPROVE_DAYS_BEFORE || 0);

module.exports = {
  CONVERSION_HOURS_PER_LEAVE,
  AUTO_APPROVE_DAYS_BEFORE
};